name: profile_stack

on:
  push:
    branches:
      - master

jobs:
  profile_stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Matt-Gleich/profile_stack@v1.4.1
        with:
          path: stack.yml
          technology_emoji: 💻
          project_emoji: ✨
